# Generated by Django 5.1.6 on 2025-08-02 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_update_achievement_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DascoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('award', 'Начисление'), ('deduct', 'Списание'), ('set', 'Установка'), ('correction', 'Корректировка')], max_length=20, verbose_name='Тип транзакции')),
                ('points_change', models.IntegerField(verbose_name='Изменение баллов')),
                ('points_before', models.PositiveIntegerField(verbose_name='Баллов до')),
                ('points_after', models.PositiveIntegerField(verbose_name='Баллов после')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция DASCOIN',
                'verbose_name_plural': 'Транзакции DASCOIN',
                'ordering': ['-created_at'],
            },
        ),
    ]
