# Generated by Django 5.1.6 on 2025-03-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
