# Generated by Django 5.1.6 on 2025-03-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_exp_profile_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
    ]
