# Generated by Django 5.1.6 on 2025-07-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='exp',
        ),
    ]
