# Generated by Django 5.1.6 on 2025-07-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_arbitrary_format',
            field=models.BooleanField(default=False, help_text='Разрешить произвольный формат номера телефона', verbose_name='Произвольный формат телефона'),
        ),
    ]
