# Generated by Django 5.1.6 on 2025-07-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_resonsible',
            field=models.BooleanField(default=False, verbose_name='Можно ли назначать ответственным'),
        ),
    ]
