# Generated by Django 5.1.6 on 2025-05-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_approved'),
        ('users', '0004_create_initial_groups'),
    ]

    operations = [
    ]
