# Generated by Django 5.1.6 on 2025-07-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exp',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт (exp)'),
        ),
    ]
