# Generated by Django 5.1.6 on 2025-07-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_phone_arbitrary_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Введите номер в формате +7XXXXXXXXXX', max_length=18, null=True, verbose_name='Номер телефона'),
        ),
    ]
