# Generated by Django 5.1.6 on 2025-07-26 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_role_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_resonsible',
        ),
        migrations.AddField(
            model_name='role',
            name='responsible_user',
            field=models.OneToOneField(blank=True, help_text='Пользователь, ответственный за данную должность', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
    ]
