# Generated by Django 5.1.6 on 2025-07-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_profile_is_resonsible_role_responsible_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dascoin_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы DASCOIN'),
        ),
    ]
