# Generated by Django 5.1.6 on 2025-10-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_create_medical_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_mentor',
            field=models.BooleanField(default=False, help_text='Пользователь с правами наставника', verbose_name='Является наставником'),
        ),
    ]
