# Generated by Django 5.1.6 on 2025-10-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_login_shown',
            field=models.BooleanField(default=False, verbose_name='Показано модальное окно при первом входе'),
        ),
    ]
