# Generated by Django 5.1.6 on 2025-11-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('points_price', models.PositiveIntegerField(verbose_name='Цена товара в баллах')),
                ('constraints', models.CharField(blank=True, choices=[('once_a_day', '1 раз в день'), ('five_times_a_week', '5 раз в неделю'), ('once_a_week', '1 раз в неделю'), ('once_a_month', '1 раз в месяц'), ('once_a_quarter', '1 раз в квартал'), ('once_every_six_months', '1 раз в 6 месяцев'), ('once_a_year', '1 раз в год')], max_length=50, null=True, verbose_name='Частота использования')),
                ('restrictions_text', models.TextField(blank=True, help_text='Подробное описание ограничений на использование товара (например: "1 раз в квартал (ограничение 2 сотрудника в отделении в 1 квартал) - ограничение по кол-ву заказов в 1 день - 1 заказ")', verbose_name='Ограничения (подробное описание)')),
                ('image', models.ImageField(blank=True, help_text='Если не указано, будет использовано изображение по умолчанию', null=True, upload_to='shop/products/', verbose_name='Изображение товара')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать товар в магазине', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар магазина',
                'verbose_name_plural': 'Товары магазина',
                'ordering': ['-created_at'],
            },
        ),
    ]
