# Generated by Django 5.1.6 on 2025-11-27 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField(verbose_name='Потрачено баллов')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус заказа')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.internalproduct', verbose_name='Товар')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Проверил администратор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ товара',
                'verbose_name_plural': 'Заказы товаров',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='shop_produc_user_id_aaf66f_idx'), models.Index(fields=['status', 'created_at'], name='shop_produc_status_721443_idx')],
            },
        ),
    ]
