# Generated by Django 5.1.6 on 2025-10-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportchat',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='supportchat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tickethistory',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='tickethistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_anonymous',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='SupportChat',
        ),
        migrations.DeleteModel(
            name='TicketHistory',
        ),
    ]
