# Generated by Django 5.1.6 on 2025-12-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_anonymous',
        ),
    ]
