# Generated by Django 5.1.6 on 2025-12-28 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_support', '0002_remove_ticket_is_anonymous_chatroom_roommessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_anonymous',
        ),
        migrations.AlterField(
            model_name='roommessage',
            name='content',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.CreateModel(
            name='RoomMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_attachments/%Y/%m/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('document', 'Документ'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tech_support.roommessage', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение сообщения',
                'verbose_name_plural': 'Вложения сообщений',
            },
        ),
    ]
