# Generated by Django 5.1.6 on 2025-12-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_support', '0003_remove_ticket_is_anonymous_alter_roommessage_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roommessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='roommessageattachment',
            name='message',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='RoomMessage',
        ),
        migrations.DeleteModel(
            name='RoomMessageAttachment',
        ),
    ]
