# Generated by Django 5.1.6 on 2026-01-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_support', '0004_remove_roommessage_room_remove_roommessage_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_anonymous',
        ),
    ]
