# Generated by Django 5.1.6 on 2026-03-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_support', '0005_remove_ticket_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Заголовок'),
        ),
    ]
