# Generated by Django 5.1.6 on 2025-05-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_userlessontrajectory'),
        ('quizzes', '0002_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='final_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quiz', verbose_name='Финальный тест'),
        ),
    ]
