# Generated by Django 5.1.6 on 2025-05-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursemessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseMessage',
        ),
    ]
