# Generated by Django 5.1.6 on 2025-07-08 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_categoryname_categoryname_parent_idx_and_more'),
        ('courses', '0009_trajectory_trajectorycourse_trajectory_courses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='lesson_course_order_idx'),
        ),
        migrations.AddIndex(
            model_name='trajectorycourse',
            index=models.Index(fields=['trajectory', 'order'], name='tc_trajectory_order_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoursetrajectory',
            index=models.Index(fields=['user', 'trajectory'], name='uct_user_trajectory_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessontrajectory',
            index=models.Index(fields=['user', 'course'], name='ult_user_course_idx'),
        ),
    ]
