stages:
  - deploy

deploy_production:
  stage: deploy
  only:
    - main
  tags:
    - prod-server-shell
  script:
    - git config --global --add safe.directory /home/django-user/pearls-site-django
    - cd /home/django-user/pearls-site-django/
    - git pull origin main
    - test -d ".venv" || python3 -m venv .venv
    - source .venv/bin/activate
    - cd myproject
    - pip install -r requirements.txt
    - test -d staticfiles && (sudo chown django-user:django-user -R staticfiles/ && sudo rm -rf staticfiles) || echo "Папка staticfiles не найдена"
    - python manage.py collectstatic --noinput
    - sudo chown www-data:www-data -R staticfiles/
    - python manage.py migrate
    - python manage.py check
    - sudo systemctl restart django
    - echo "Готово!!!"