# Generated by Django 5.1.6 on 2025-08-09 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tech_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tech_support.ticket', verbose_name='Связанный тикет'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('dascoin', 'Начисление/списание DASCOIN'), ('course_assigned', 'Назначение курса'), ('trajectory_assigned', 'Назначение траектории'), ('platform_update', 'Обновление платформы'), ('course_reminder', 'Напоминание о курсе'), ('lesson_actualization', 'Напоминание об актуализации урока'), ('ticket_status', 'Изменение статуса тикета'), ('ticket_comment', 'Новое сообщение по тикету')], max_length=50, verbose_name='Тип уведомления'),
        ),
    ]
