# Generated by Django 5.1.6 on 2025-11-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_related_quiz_result_and_more'),
        ('shop', '0002_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productorder', verbose_name='Связанный заказ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('dascoin', 'Начисление/списание DASCOIN'), ('course_assigned', 'Назначение курса'), ('trajectory_assigned', 'Назначение траектории'), ('platform_update', 'Обновление платформы'), ('course_reminder', 'Напоминание о курсе'), ('lesson_actualization', 'Напоминание об актуализации урока'), ('ticket_status', 'Изменение статуса тикета'), ('ticket_comment', 'Новое сообщение по тикету'), ('quiz_reviewed', 'Оценка теста наставником'), ('order_status', 'Изменение статуса заказа')], max_length=50, verbose_name='Тип уведомления'),
        ),
    ]
