# Generated by Django 5.1.6 on 2026-01-16 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_chatroomnotificationsettings'),
        ('notifications', '0004_notification_related_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.chatroom', verbose_name='Связанная комната чата'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('dascoin', 'Начисление/списание DASCOIN'), ('course_assigned', 'Назначение курса'), ('trajectory_assigned', 'Назначение траектории'), ('platform_update', 'Обновление платформы'), ('course_reminder', 'Напоминание о курсе'), ('lesson_actualization', 'Напоминание об актуализации урока'), ('ticket_status', 'Изменение статуса тикета'), ('ticket_comment', 'Новое сообщение по тикету'), ('quiz_reviewed', 'Оценка теста наставником'), ('order_status', 'Изменение статуса заказа'), ('chat_message', 'Новое сообщение в чате')], max_length=50, verbose_name='Тип уведомления'),
        ),
    ]
