# Generated by Django 5.1.6 on 2025-12-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_related_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[
                ('dascoin', 'Начисление/списание DASCOIN'), 
                ('course_assigned', 'Назначение курса'), 
                ('trajectory_assigned', 'Назначение траектории'), 
                ('platform_update', 'Обновление платформы'), 
                ('course_reminder', 'Напоминание о курсе'), 
                ('lesson_actualization', 'Напоминание об актуализации урока'), 
                ('ticket_status', 'Изменение статуса тикета'), 
                ('ticket_comment', 'Новое сообщение по тикету'), 
                ('quiz_reviewed', 'Оценка теста наставником'), 
                ('order_status', 'Изменение статуса заказа'), 
                ('course_materials_updated', 'Обновление материалов в завершенном курсе')
                ], 
                max_length=50, verbose_name='Тип уведомления'
            ),
        ),
    ]
