# Generated by Django 5.1.6 on 2026-01-08 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_notification_type'),
        ('quizzes', '0017_homework_homeworksubmission_homeworksubmissionimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_homework_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.homeworksubmission', verbose_name='Связанный ответ на задание'),
        ),
    ]
