# Generated by Django 5.1.6 on 2026-02-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_related_chat_room_and_more'),
        ('notifications', '0007_notification_related_homework_submission'),
    ]

    operations = [
    ]
