# Generated by Django 5.1.6 on 2026-02-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_add_related_sender_to_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('dascoin', 'Начисление/списание DASCOIN'), ('course_assigned', 'Назначение курса'), ('trajectory_assigned', 'Назначение траектории'), ('platform_update', 'Обновление платформы'), ('course_reminder', 'Напоминание о курсе'), ('lesson_actualization', 'Напоминание об актуализации урока'), ('ticket_status', 'Изменение статуса тикета'), ('ticket_comment', 'Новое сообщение по тикету'), ('quiz_reviewed', 'Оценка теста наставником'), ('homework_reviewed', 'Оценка задания наставником'), ('order_status', 'Изменение статуса заказа'), ('chat_message', 'Новое сообщение в чате'), ('course_materials_updated', 'Обновление материалов в завершенном курсе'), ('incident_course_overdue', 'Просрочен курс-инцидент')], max_length=50, verbose_name='Тип уведомления'),
        ),
    ]
