# Generated by Django 5.1.6 on 2026-04-12 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True, help_text='Краткое описание для карточки в ленте')),
                ('content', models.TextField()),
                ('news_type', models.CharField(choices=[('new_employees', 'Новые сотрудники'), ('events', 'Мероприятия'), ('birthdays', 'Дни рождения'), ('corporate_events', 'Корпоративная жизнь'), ('internal_events', 'Праздники компании'), ('new_year', 'Новый год'), ('other', 'Другое')], db_index=True, default='other', max_length=32)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='news/main/')),
                ('video', models.FileField(blank=True, null=True, upload_to='news/video/')),
                ('video_embed_url', models.URLField(blank=True, help_text='Ссылка на видео (YouTube, VK и т.п.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='news.newsitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
