# Generated by Django 5.1.6 on 2026-04-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='excerpt',
            new_name='description',
        ),
    ]
