# Generated by Django 5.1.6 on 2026-04-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='news_type',
            field=models.CharField(choices=[('new_employees', 'Новые сотрудники'), ('corporate_events', 'Корпоративная жизнь'), ('other', 'Другое')], db_index=True, default='other', max_length=100),
        ),
    ]
