# Generated by Django 5.1.6 on 2025-07-01 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название инцидента')),
                ('incident_type', models.CharField(choices=[('test_fail', 'Провал теста'), ('incident', 'Инцидент'), ('regulation_change', 'Изменение регламента')], max_length=32, verbose_name='Тип инцидента')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('role', models.CharField(blank=True, max_length=128, verbose_name='Роль')),
                ('error_type', models.CharField(blank=True, max_length=128, verbose_name='Тип ошибки')),
                ('topic', models.CharField(blank=True, max_length=128, verbose_name='Тема')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('resolved', 'Решён')], default='new', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('related_documents', models.ManyToManyField(blank=True, to='builder.document', verbose_name='Документы из БЗ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
    ]
