# Generated by Django 5.1.6 on 2025-07-08 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_incident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categoryname',
            index=models.Index(fields=['parent'], name='categoryname_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['user'], name='incident_user_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incident_status_idx'),
        ),
    ]
