# Generated by Django 5.1.6 on 2025-07-08 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_lessonversion'),
        ('courses', '0010_lesson_lesson_course_order_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonUpdateControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='№ версии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateField(verbose_name='Дата обновления')),
                ('next_update_date', models.DateField(verbose_name='Следующая дата обновления')),
                ('period_between_updates', models.PositiveIntegerField(verbose_name='Период между последними обновлениями, дней')),
                ('standard_period', models.PositiveIntegerField(default=180, verbose_name='Стандарт периода обновлений, дней')),
                ('responsible_role', models.CharField(max_length=128, verbose_name='Ответственный (роль)')),
                ('responsible_fio', models.CharField(max_length=128, verbose_name='ФИО сотрудника')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_controls', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Контроль обновлений урока',
                'verbose_name_plural': 'Контроль обновлений уроков',
                'ordering': ['-update_date', '-created_at'],
            },
        ),
    ]
