# Generated by Django 5.1.6 on 2025-07-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_lessonupdatecontrol'),
        ('courses', '0010_lesson_lesson_course_order_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCategoryMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в категории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirrored_lessons', to='builder.categoryname', verbose_name='Категория зеркала')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirrors', to='courses.lesson', verbose_name='Зеркалируемый урок')),
            ],
            options={
                'verbose_name': 'Зеркало урока',
                'verbose_name_plural': 'Зеркала уроков',
                'ordering': ['order'],
                'unique_together': {('lesson', 'category')},
            },
        ),
    ]
