# Generated by Django 5.1.6 on 2025-07-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_alter_dictionaryterm_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonUpdateControl',
        ),
    ]
