# Generated by Django 5.1.6 on 2025-07-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_delete_lessonupdatecontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonversion',
            name='next_update',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего обновления'),
        ),
        migrations.AddField(
            model_name='lessonversion',
            name='update_period_days',
            field=models.IntegerField(default=90, verbose_name='Стандарт периода обновлений, дней'),
        ),
    ]
