# Generated by Django 5.1.6 on 2025-07-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_categoryname_allowed_groups'),
        ('courses', '0011_lesson_created_at'),
        ('users', '0016_remove_profile_is_resonsible_role_responsible_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAllowedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_roles', to='courses.lesson', verbose_name='Урок')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Разрешенная должность для урока',
                'verbose_name_plural': 'Разрешенные должности для уроков',
                'ordering': ['role__name'],
                'unique_together': {('lesson', 'role')},
            },
        ),
    ]
