# Generated by Django 5.1.6 on 2025-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
