# Generated by Django 5.1.6 on 2025-08-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_quizresult_quizresult_user_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
