# Generated by Django 5.1.6 on 2025-08-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_userprogress_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='read',
        ),
    ]
