# Generated by Django 5.1.6 on 2025-08-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_userprogress_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(blank=True, help_text='Для открытых ответов: None = не оценено', null=True),
        ),
    ]
