# Generated by Django 5.1.6 on 2025-08-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_course_description'),
        ('myapp', '0015_alter_useranswer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
    ]
