# Generated by Django 5.1.6 on 2025-10-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_quizresult_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='excluded_from_limit',
            field=models.BooleanField(default=False, help_text='Если True, эта попытка не учитывается при проверке лимита попыток', verbose_name='Исключен из лимита попыток'),
        ),
    ]
