# Generated by Django 5.1.6 on 2025-11-02 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_quizresult_excluded_from_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='mentor_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий наставника'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Проверил наставник'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершен'), ('pending', 'Ожидает проверки')], default='completed', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='score_points',
            field=models.FloatField(blank=True, default=None, help_text='Для открытых вопросов: 0 (неверно), 0.5 (частично верно), 1 (верно)', null=True, verbose_name='Баллы'),
        ),
    ]
