# Generated by Django 5.1.6 on 2025-11-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_quizresult_mentor_comment_quizresult_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.FloatField(),
        ),
    ]
