# Generated by Django 5.1.6 on 2025-11-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_quizresult_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершен'), ('pending', 'Ожидает проверки'), ('reviewed', 'Проверен')], default='completed', max_length=20, verbose_name='Статус'),
        ),
    ]
