# Generated by Django 5.1.6 on 2025-11-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_quizresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
