# Generated by Django 5.1.6 on 2025-11-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_useranswer_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Дата, до которой нужно завершить курс', null=True, verbose_name='Срок завершения курса'),
        ),
    ]
