# Generated by Django 5.1.6 on 2025-11-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_usercourse_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('started', 'Начат'), ('completed', 'Завершен'), ('blocked', 'Заблокирован')], default='available', max_length=20),
        ),
    ]
