# Generated by Django 5.1.6 on 2026-01-05 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_course_default_deadline_days'),
        ('myapp', '0024_manualcourseunassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'course', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'course'], name='userprogress_user_course_idx'),
        ),
    ]
