# Generated by Django 5.1.6 on 2025-05-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один правильный ответ'), ('multiple', 'Несколько правильных ответов')], default='single', max_length=10),
        ),
    ]
