# Generated by Django 5.1.6 on 2025-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_answer_answer_question_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='points',
            field=models.PositiveIntegerField(default=10, verbose_name='Количество DASCOIN за прохождение теста'),
        ),
    ]
