# Generated by Django 5.1.6 on 2025-08-14 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_answer_text_alter_question_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempt_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = без ограничений', verbose_name='Ограничение попыток'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='pass_threshold',
            field=models.PositiveIntegerField(default=70, verbose_name='Проходной балл (%)'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='Номер попытки')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка теста',
                'verbose_name_plural': 'Попытки тестов',
                'indexes': [models.Index(fields=['user', 'quiz'], name='quiz_attempt_user_quiz_idx')],
                'unique_together': {('user', 'quiz', 'attempt_number')},
            },
        ),
    ]
