# Generated by Django 5.1.6 on 2025-08-14 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_quiz_attempt_limit_quiz_pass_threshold_quizattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата блокировки')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Блокировка теста',
                'verbose_name_plural': 'Блокировки тестов',
                'indexes': [models.Index(fields=['user', 'quiz'], name='quiz_lock_user_quiz_idx')],
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
