# Generated by Django 5.1.6 on 2025-08-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_course_description'),
        ('quizzes', '0009_quizlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='course_quizzes', to='courses.course', verbose_name='Курсы, в которых используется тест'),
        ),
    ]
