# Generated by Django 5.1.6 on 2025-08-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_quiz_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в курсе'),
        ),
    ]
