# Generated by Django 5.1.6 on 2025-10-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_quiz_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один правильный ответ'), ('multiple', 'Несколько правильных ответов'), ('text', 'Открытый ответ'), ('match', 'Соответствие')], default='single', max_length=20),
        ),
    ]
