# Generated by Django 5.1.6 on 2025-10-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_answers/', verbose_name='Изображение'),
        ),
    ]
