# Generated by Django 5.1.6 on 2025-10-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_answer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один правильный ответ'), ('multiple', 'Несколько правильных ответов'), ('text', 'Открытый ответ'), ('match', 'Соответствие'), ('sequence', 'Последовательность')], default='single', max_length=20),
        ),
    ]
