# Generated by Django 5.1.6 on 2025-10-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = без ограничения по времени', verbose_name='Время на прохождение (минуты)'),
        ),
    ]
