# Generated by Django 5.1.6 on 2025-11-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_quiz_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mentor_instruction',
            field=models.TextField(blank=True, help_text='Текст, который будет отображаться наставнику при проверке открытого вопроса', null=True, verbose_name='Комментарий для наставника'),
        ),
    ]
