# Generated by Django 5.1.6 on 2026-01-08 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_course_default_deadline_days'),
        ('quizzes', '0016_question_mentor_instruction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Текст задания')),
                ('mentor_comment', models.TextField(blank=True, help_text='Отображается наставнику при проверке (по клику на иконку ?)', null=True, verbose_name='Комментарий для наставника')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в курсе')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Количество DASCOIN за выполнение задания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('courses', models.ManyToManyField(blank=True, related_name='course_homeworks', to='courses.course', verbose_name='Курсы, в которых используется задание')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Ответ пользователя')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('correct', 'Правильно'), ('incorrect', 'Неправильно')], default='pending', max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('mentor_feedback', models.TextField(blank=True, null=True, verbose_name='Комментарий наставника к ответу')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.homework', verbose_name='Задание')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='Проверено (кем)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на задание',
                'verbose_name_plural': 'Ответы на задания',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homework_submissions/%Y/%m/', verbose_name='Изображение')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quizzes.homeworksubmission', verbose_name='Ответ на задание')),
            ],
            options={
                'verbose_name': 'Изображение к ответу',
                'verbose_name_plural': 'Изображения к ответам',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['user', 'homework'], name='hw_sub_user_hw_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['status'], name='hw_sub_status_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['submitted_at'], name='hw_sub_submitted_idx'),
        ),
    ]
