# Generated by Django 5.1.6 on 2025-07-08 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_categoryname_categoryname_parent_idx_and_more'),
        ('courses', '0010_lesson_lesson_course_order_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('video_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID видео с Rutube')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий к изменению')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='courses.lesson', verbose_name='Урок')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Версия урока',
                'verbose_name_plural': 'Версии уроков',
                'ordering': ['-version', '-updated_at'],
                'unique_together': {('lesson', 'version')},
            },
        ),
    ]
