# Generated by Django 5.1.6 on 2025-07-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_lessoncategorymirror'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='Термин')),
                ('definition', models.TextField(verbose_name='Определение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Слово словаря',
                'verbose_name_plural': 'Словарь',
                'ordering': ['order', 'term'],
            },
        ),
    ]
