# Generated by Django 5.1.6 on 2025-07-17 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_lessonversion_next_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionarySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отдела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Отдел словаря',
                'verbose_name_plural': 'Отделы словаря',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='dictionaryterm',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dict_photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='dictionaryterm',
            name='slang',
            field=models.CharField(blank=True, max_length=200, verbose_name='Сленг'),
        ),
        migrations.AddField(
            model_name='dictionaryterm',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='builder.dictionarysection', verbose_name='Отдел'),
            preserve_default=False,
        ),
    ]
