# Generated by Django 5.1.6 on 2025-07-17 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0012_dictionarysection_dictionaryterm_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryterm',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='builder.dictionarysection', verbose_name='Отдел'),
        ),
    ]
