# Generated by Django 5.1.6 on 2025-07-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('builder', '0013_alter_dictionaryterm_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryname',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, которым доступна эта категория и все её подкатегории/уроки в БЗ', related_name='allowed_categories', to='auth.group', verbose_name='Доступен для групп'),
        ),
    ]
