# Generated by Django 5.1.6 on 2025-08-25 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0015_lessonallowedrole'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('copy', 'Копирование'), ('move', 'Перемещение'), ('mirror', 'Создание зеркала'), ('reorder', 'Изменение порядка'), ('actualize', 'Актуализация')], max_length=20, verbose_name='Действие')),
                ('object_id', models.PositiveIntegerField()),
                ('object_name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Старые значения')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Новые значения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='auditlog_user_idx'), models.Index(fields=['timestamp'], name='auditlog_timestamp_idx'), models.Index(fields=['action'], name='auditlog_action_idx'), models.Index(fields=['content_type', 'object_id'], name='auditlog_object_idx'), models.Index(fields=['model_name'], name='auditlog_model_idx')],
            },
        ),
    ]
