# Generated by Django 5.1.6 on 2025-11-04 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0016_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='error_type',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='related_documents',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='role',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='topic',
        ),
        migrations.AddField(
            model_name='incident',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата решения'),
        ),
        migrations.AddField(
            model_name='incident',
            name='responsible_users',
            field=models.ManyToManyField(blank=True, related_name='responsible_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные за инцидент'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий/описание'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('informational', 'Информационный'), ('educational', 'Обучающий')], max_length=32, verbose_name='Тип инцидента'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('assigned', 'Назначен'), ('resolved', 'Завершён'), ('declined', 'Отклонён')], default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название инцидента (описание)'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Кто зафиксировал'),
        ),
    ]
