# Generated by Django 5.1.6 on 2025-11-05 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0017_remove_incident_error_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Кому назначен'),
        ),
    ]
