# Generated by Django 5.1.6 on 2025-11-05 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0018_incident_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='responsible_users',
        ),
        migrations.AddField(
            model_name='incident',
            name='initiator_users',
            field=models.ManyToManyField(blank=True, related_name='initiator_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор инцидента'),
        ),
    ]
