# Generated by Django 5.1.6 on 2025-11-05 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0018_incident_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='incident',
            name='violators',
            field=models.ManyToManyField(blank=True, related_name='violator_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Нарушитель'),
        ),
    ]
