# Generated by Django 5.1.6 on 2025-11-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0019_remove_incident_responsible_users_incident_violators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='responsible_users',
        ),
    ]
