# Generated by Django 5.1.6 on 2025-11-05 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0019_remove_incident_responsible_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='initiator_users',
        ),
        migrations.AddField(
            model_name='incident',
            name='violators',
            field=models.ManyToManyField(blank=True, related_name='violator_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Виновник/нарушитель инцидента'),
        ),
    ]
