# Generated by Django 5.1.6 on 2025-11-09 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0020_remove_incident_initiator_users_incident_violators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='mentors_time_to_check',
            field=models.PositiveIntegerField(default=2, help_text='Количество дней для проверки наставником', verbose_name='Время на проверку (дней)'),
        ),
        migrations.AddField(
            model_name='incident',
            name='responsible_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentored_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий наставник'),
        ),
    ]
