# Generated by Django 5.1.6 on 2025-11-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0020_remove_incident_initiator_users_incident_violators'),
        ('builder', '0021_add_violators_table'),
    ]

    operations = [
    ]
