# Generated by Django 5.1.6 on 2025-11-10 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0021_incident_mentors_time_to_check_and_more'),
        ('courses', '0026_course_mentors_time_to_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='courses.course', verbose_name='Курс-инцидент'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название инцидента'),
        ),
    ]
