# Generated by Django 5.1.6 on 2025-11-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0022_add_course_to_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('accepted', 'Принят'), ('assigned', 'Назначен'), ('resolved', 'Завершён'), ('declined', 'Отклонён')], help_text='Статус до отклонения', max_length=32, null=True, verbose_name='Предыдущий статус'),
        ),
    ]
