# Generated by Django 5.1.6 on 2025-11-16 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0023_add_previous_status_to_incident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_expert', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за актуальность курса'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('accepted', 'Принят'), ('assigned', 'Назначен'), ('studies_completed', 'Обучение завершено'), ('resolved', 'Завершён'), ('declined', 'Отклонён')], help_text='Статус до отклонения', max_length=32, null=True, verbose_name='Предыдущий статус'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('assigned', 'Назначен'), ('studies_completed', 'Обучение завершено'), ('resolved', 'Завершён'), ('declined', 'Отклонён')], default='new', max_length=32, verbose_name='Статус'),
        ),
    ]
