# Generated by Django 5.1.6 on 2025-11-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0024_incident_expert_alter_incident_previous_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned_to_time_to_complete',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='Количество дней для завершения обучения назначенными/нарушителями', null=True, verbose_name='Время на завершение обучения (дней)'),
        ),
        migrations.AddField(
            model_name='incident',
            name='expert_time_to_complete',
            field=models.PositiveIntegerField(blank=True, default=3, null=True, verbose_name='Время на завершение/актуализацию (дней)'),
        ),
    ]
