# Generated by Django 5.1.6 on 2025-11-19 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0026_ipr'),
        ('users', '0023_profile_first_login_shown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала ИПР')),
                ('title', models.CharField(max_length=255, verbose_name='Тема ИПР (название модуля)')),
                ('status', models.CharField(blank=True, help_text='Пока прочерк', max_length=100, null=True, verbose_name='Статус')),
                ('intermediate_control', models.CharField(blank=True, help_text='Пока прочерк', max_length=255, null=True, verbose_name='Промежуточный контроль')),
                ('deadline', models.DateTimeField(blank=True, help_text='Пока прочерк', null=True, verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department', verbose_name='Отделение (группа)')),
                ('ipr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='builder.ipr', verbose_name='ИПР')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_ipr_modules', to=settings.AUTH_USER_MODEL, verbose_name='Наставник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipr_modules', to=settings.AUTH_USER_MODEL, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Модуль ИПР',
                'verbose_name_plural': 'Модули ИПР',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ipr'], name='iprmodule_ipr_idx'), models.Index(fields=['user'], name='iprmodule_user_idx'), models.Index(fields=['mentor'], name='iprmodule_mentor_idx')],
            },
        ),
    ]
