# Generated by Django 5.1.6 on 2025-11-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0027_iprmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprmodule',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания ИПР'),
        ),
    ]
