# Generated by Django 5.1.6 on 2025-11-20 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0028_iprmodule_end_date'),
        ('users', '0023_profile_first_login_shown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iprmodule',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head_ipr_modules', to=settings.AUTH_USER_MODEL, verbose_name='Зав отделением'),
        ),
        migrations.AddField(
            model_name='iprmodule',
            name='diagnostics',
            field=models.TextField(blank=True, help_text='Описание проблем и диагностики', null=True, verbose_name='Диагностика / Проблема'),
        ),
        migrations.AddField(
            model_name='iprmodule',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_ipr_modules', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AddIndex(
            model_name='iprmodule',
            index=models.Index(fields=['supervisor'], name='iprmodule_supervisor_idx'),
        ),
        migrations.AddIndex(
            model_name='iprmodule',
            index=models.Index(fields=['department_head'], name='iprmodule_dept_head_idx'),
        ),
    ]
