# Generated by Django 5.1.6 on 2025-11-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0029_iprmodule_department_head_iprmodule_diagnostics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprmodule',
            name='goals',
            field=models.TextField(blank=True, help_text='Описание целей модуля ИПР', null=True, verbose_name='Цели'),
        ),
    ]
