# Generated by Django 5.1.6 on 2025-11-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0030_iprmodule_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRModuleIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название показателя', max_length=255, verbose_name='Показатель')),
                ('point_a', models.TextField(blank=True, help_text='Начальное состояние', null=True, verbose_name='Точка А')),
                ('intermediate_point', models.TextField(blank=True, help_text='Промежуточное состояние', null=True, verbose_name='Промежуточная точка')),
                ('stage_deadline', models.DateTimeField(blank=True, help_text='Дата и время срока этапа', null=True, verbose_name='Срок этапа')),
                ('point_b', models.TextField(blank=True, help_text='Целевое состояние', null=True, verbose_name='Точка Б')),
                ('fact', models.TextField(blank=True, help_text='Фактическое состояние', null=True, verbose_name='Факт')),
                ('deadline', models.DateTimeField(blank=True, help_text='Дата и время дедлайна', null=True, verbose_name='Дедлайн')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='builder.iprmodule', verbose_name='Модуль ИПР')),
            ],
            options={
                'verbose_name': 'Показатель модуля ИПР',
                'verbose_name_plural': 'Показатели модулей ИПР',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['module'], name='iprmoduleindicator_module_idx')],
            },
        ),
    ]
