# Generated by Django 5.1.6 on 2025-11-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0031_iprmoduleindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprmodule',
            name='comment',
            field=models.TextField(blank=True, help_text='Произвоьные комментарии по факту выполненной работы', null=True, verbose_name='Комментарий'),
        ),
    ]
