# Generated by Django 5.1.6 on 2025-11-20 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('builder', '0032_iprmodule_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprmodule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Отделение (группа)'),
        ),
    ]
