# Generated by Django 5.1.6 on 2025-11-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0033_alter_iprmodule_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprmodule',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала ИПР'),
        ),
    ]
