# Generated by Django 5.1.6 on 2025-11-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0034_alter_iprmodule_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipr',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('active', 'Активен'), ('completed', 'Завершен'), ('paused', 'Приостановлен'), ('cancelled', 'Отменен')], default='active', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='iprmodule',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('active', 'Активен'), ('completed', 'Завершен'), ('paused', 'Приостановлен'), ('cancelled', 'Отменен')], default='new', help_text='Пока прочерк', max_length=100, verbose_name='Статус'),
        ),
    ]
