# Generated by Django 5.1.6 on 2026-01-13 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0035_alter_ipr_status_alter_iprmodule_status'),
        ('courses', '0031_course_default_deadline_days'),
        ('quizzes', '0017_homework_homeworksubmission_homeworksubmissionimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('video_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID видео с Rutube')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок урока')),
                ('required_time', models.PositiveIntegerField(default=7, verbose_name='Необходимое время (минуты)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус')),
                ('review_comment', models.TextField(blank=True, verbose_name='Комментарий при рассмотрении')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_lessons', to='builder.categoryname', verbose_name='Категория')),
                ('courses', models.ManyToManyField(blank=True, related_name='draft_lessons', to='courses.course', verbose_name='Курсы')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('final_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quiz', verbose_name='Финальный тест')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='courses.lesson', verbose_name='Урок')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
            ],
            options={
                'verbose_name': 'Черновик урока',
                'verbose_name_plural': 'Черновики уроков',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lesson', 'status'], name='lessondraft_lesson_status_idx'), models.Index(fields=['created_by'], name='lessondraft_created_by_idx'), models.Index(fields=['status'], name='lessondraft_status_idx')],
            },
        ),
    ]
