# Generated by Django 5.1.6 on 2026-01-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0036_lessondraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessondraft',
            name='submit_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к черновику'),
        ),
    ]
