# Generated by Django 5.1.6 on 2026-02-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0037_lessondraft_submit_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessondraft',
            name='saved_at_least_once',
            field=models.BooleanField(default=False, verbose_name='Черновик сохранялся'),
        ),
    ]
