# Generated by Django 5.1.6 on 2026-02-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0038_lessondraft_saved_at_least_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessondraft',
            name='content_element_status',
            field=models.CharField(choices=[('actual', 'Готово (актуально сейчас)'), ('needs_work', 'Нужно доработать')], default='actual', max_length=20, verbose_name='Текст (актуально/нужно доработать)'),
        ),
        migrations.AddField(
            model_name='lessondraft',
            name='links_element_status',
            field=models.CharField(choices=[('actual', 'Готово (актуально сейчас)'), ('needs_work', 'Нужно доработать')], default='actual', max_length=20, verbose_name='Ссылки (актуально/нужно доработать)'),
        ),
        migrations.AddField(
            model_name='lessondraft',
            name='video_element_status',
            field=models.CharField(choices=[('actual', 'Готово (актуально сейчас)'), ('needs_work', 'Нужно доработать')], default='actual', max_length=20, verbose_name='Видео (актуально/нужно доработать)'),
        ),
    ]
