# Generated by Django 5.1.6 on 2025-04-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(blank=True, help_text='Пример: https://rutube.ru/video/VIDEO_ID/ - вводите только VIDEO_ID', max_length=100, null=True, verbose_name='ID видео с Rutube'),
        ),
    ]
