# Generated by Django 5.1.6 on 2025-05-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
        ('courses', '0006_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='builder.categoryname', verbose_name='Категория'),
        ),
    ]
