# Generated by Django 5.1.6 on 2025-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0007_lesson_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, которым доступен этот курс', to='auth.group', verbose_name='Доступен для групп'),
        ),
    ]
