# Generated by Django 5.1.6 on 2025-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0015_lessonallowedrole'),
        ('courses', '0013_alter_trajectory_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lesson',
            name='lesson_course_order_idx',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='course_lessons', to='courses.course', verbose_name='Курсы, в которых используется урок'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['order'], name='lesson_order_idx'),
        ),
    ]
