# Generated by Django 5.1.6 on 2025-08-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_certificate_trajectory_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='course_images/default.jpg', null=True, upload_to='course_images/', verbose_name='Изображение курса'),
        ),
    ]
