# Generated by Django 5.1.6 on 2025-08-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(blank=True, help_text='ПОЛЕ НЕ ИСПОЛЬЗУЕТСЯ', max_length=100, null=True, verbose_name='ID видео с Rutube (не используется)'),
        ),
    ]
