# Generated by Django 5.1.6 on 2025-09-11 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_course_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255, verbose_name='Название клиники')),
                ('initial_month', models.CharField(max_length=7, verbose_name='Начальный месяц')),
                ('doctors_count', models.PositiveIntegerField(verbose_name='Количество врачей')),
                ('chairs_count', models.PositiveIntegerField(verbose_name='Количество кресел')),
                ('work_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Часы работы в день')),
                ('days_month_1', models.PositiveIntegerField(verbose_name='Дни месяц 1')),
                ('days_month_2', models.PositiveIntegerField(verbose_name='Дни месяц 2')),
                ('days_month_3', models.PositiveIntegerField(verbose_name='Дни месяц 3')),
                ('days_month_4', models.PositiveIntegerField(verbose_name='Дни месяц 4')),
                ('days_month_5', models.PositiveIntegerField(verbose_name='Дни месяц 5')),
                ('days_month_6', models.PositiveIntegerField(verbose_name='Дни месяц 6')),
                ('doctors_data', models.JSONField(help_text='JSON с данными врачей и их метриками', verbose_name='Данные врачей')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заполненная форма метрик',
                'verbose_name_plural': 'Заполненные формы метрик',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'submitted_at'], name='metrics_user_date_idx'), models.Index(fields=['submitted_at'], name='metrics_date_idx')],
            },
        ),
    ]
