# Generated by Django 5.1.6 on 2025-09-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_metricssubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricssubmission',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='hours_saturday',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Часы работы в субботу'),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='hours_sunday',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Часы работы в воскресенье'),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='hours_weekdays',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Часы работы в будни'),
        ),
    ]
