# Generated by Django 5.1.6 on 2025-10-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_metricssubmission_work_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='course_lessons', to='courses.course', verbose_name='Выберите курсы, куда добавить урок'),
        ),
    ]
