# Generated by Django 5.1.6 on 2025-10-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_lesson_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='required_time',
            field=models.PositiveIntegerField(default=7, help_text='Время в минутах, необходимое для прохождения урока', verbose_name='Необходимое время (минуты)'),
        ),
    ]
