# Generated by Django 5.1.6 on 2025-11-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_lesson_required_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_incident',
            field=models.BooleanField(default=False, help_text='Курс-инцидент не попадает в общую статистику', verbose_name='Инцидент'),
        ),
    ]
