# Generated by Django 5.1.6 on 2025-11-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_course_responsible_mentor_alter_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mentors_time_to_check',
            field=models.PositiveIntegerField(default=2, help_text='Количество дней для проверки наставником', verbose_name='Время на проверку (дней)'),
        ),
    ]
