# Generated by Django 5.1.6 on 2025-11-23 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_course_mentors_time_to_check'),
        ('quizzes', '0016_question_mentor_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='final_quiz',
            field=models.ForeignKey(blank=True, help_text='Связанный с уроком, обязательный тест', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quiz', verbose_name='Финальный тест'),
        ),
    ]
