# Generated by Django 5.1.6 on 2025-11-24 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_lesson_final_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTrajectoryUnassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unassigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отмены назначения')),
                ('reason', models.TextField(blank=True, help_text='Опционально', verbose_name='Причина отмены')),
                ('trajectory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.trajectory')),
                ('unassigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_trajectory_unassignments', to=settings.AUTH_USER_MODEL, verbose_name='Кто отменил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_trajectory_unassignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ручная отмена назначения траектории',
                'verbose_name_plural': 'Ручные отмены назначений траекторий',
                'indexes': [models.Index(fields=['user', 'trajectory'], name='courses_man_user_id_328392_idx')],
                'unique_together': {('user', 'trajectory')},
            },
        ),
    ]
