# Generated by Django 5.1.6 on 2025-11-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_manualtrajectoryunassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricssubmission',
            name='currency',
            field=models.CharField(choices=[('rub', 'Рубли (₽)'), ('kzt', 'Тенге (₸)')], default='rub', max_length=3, verbose_name='Валюта'),
        ),
    ]
