# Generated by Django 5.1.6 on 2025-12-04 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_metricssubmission_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Назначено пользователем')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='courses.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Назначенный урок пользователю',
                'verbose_name_plural': 'Назначенные уроки пользователям',
                'indexes': [models.Index(fields=['user'], name='userlesson_user_idx'), models.Index(fields=['lesson'], name='userlesson_lesson_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
