# Generated by Django 5.1.6 on 2025-12-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_userlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='default_deadline_days',
            field=models.PositiveIntegerField(default=7, help_text='Количество дней, которое дается на завершение курса назначенным пользователям. По умолчанию используется при назначении курса, если не указано другое значение.', verbose_name='Срок завершения курса (дней)'),
        ),
    ]
