# Generated by Django 5.1.6 on 2025-10-29 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegated_permissions', models.TextField(help_text='Описание делегируемых прав и полномочий', verbose_name='Делегируемые права')),
                ('start_datetime', models.DateTimeField(help_text='С какого момента права становятся активными', verbose_name='Дата и время начала')),
                ('end_datetime', models.DateTimeField(help_text='До какого момента права действуют', verbose_name='Дата и время окончания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, choices=[('vacation', 'Отпуск'), ('sick_leave', 'Больничный'), ('replacement', 'Замена сотрудника'), ('other', 'Другое')], max_length=20, null=True, verbose_name='Причина делегирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('confirmed_by_assistant', models.BooleanField(default=False, verbose_name='Подтверждено бизнес-ассистентом')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL, verbose_name='Принимающий')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL, verbose_name='Передающий')),
            ],
            options={
                'verbose_name': 'Делегирование',
                'verbose_name_plural': 'Делегирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
