# Generated by Django 5.1.6 on 2025-12-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='delegated_permissions',
            field=models.TextField(blank=True, help_text='Описание делегируемых прав и полномочий', null=True, verbose_name='Делегируемые права'),
        ),
    ]
