# Generated by Django 5.1.6 on 2025-12-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegation', '0002_alter_delegation_delegated_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='closing_section',
            field=models.TextField(blank=True, null=True, verbose_name='Какой участок закрывается'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='project',
            field=models.TextField(blank=True, null=True, verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='restrictions',
            field=models.TextField(blank=True, null=True, verbose_name='Ограничения'),
        ),
    ]
