# Generated by Django 5.1.6 on 2026-03-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegation', '0003_delegation_closing_section_delegation_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='До какого момента права действуют', null=True, verbose_name='Дата и время окончания'),
        ),
    ]
