# Generated by Django 5.1.6 on 2026-04-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_webpushsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webpushsubscription',
            new_name='messenger_w_user_id_0ae307_idx',
            old_name='messenger_w_user_id_idx',
        ),
    ]
