# Generated by Django 5.1.6 on 2025-05-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
