# Generated by Django 5.1.6 on 2025-05-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_quizresult_passed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': 'Курс пользователя', 'verbose_name_plural': 'Курсы пользователей'},
        ),
    ]
