# Generated by Django 5.1.6 on 2025-05-19 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_usercourse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Версия')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата релиза')),
                ('type', models.CharField(choices=[('feature', '🎁 Новый функционал'), ('bugfix', '🐞 Исправление ошибок'), ('improvement', '⚡ Улучшение'), ('security', '🔒 Безопасность')], max_length=20, verbose_name='Тип изменения')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('related_link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Запись изменений',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-release_date', '-order'],
            },
        ),
    ]
