# Generated by Django 5.1.6 on 2025-05-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_changelog'),
        ('myapp', '0008_useranswer_answer_text_alter_useranswer_user'),
    ]

    operations = [
    ]
