# Generated by Django 5.1.6 on 2025-03-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='course_complete_animation_shown',
            field=models.BooleanField(default=False),
        ),
    ]
