# Generated by Django 5.1.6 on 2025-05-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_merge_20250519_2033'),
        ('myapp', '0009_merge_20250520_1346'),
    ]

    operations = [
    ]
