# Generated by Django 5.1.6 on 2025-03-18 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['stage']},
        ),
        migrations.AddField(
            model_name='course',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Обязательный курс'),
        ),
        migrations.AddField(
            model_name='course',
            name='stage',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Этап обучения'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveBigIntegerField(default=0, verbose_name='Порядок отображения')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='myapp.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.category', verbose_name='Категория'),
        ),
    ]
