# Generated by Django 5.1.6 on 2025-06-25 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_allowed_groups'),
        ('myapp', '0010_merge_20250521_1250'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('started', 'Начат'), ('completed', 'Завершен')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['status'], name='myapp_userc_status_67444b_idx'),
        ),
    ]
