# Generated by Django 5.1.6 on 2025-07-08 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_lesson_course_order_idx_and_more'),
        ('myapp', '0011_remove_usercourse_is_completed_usercourse_status_and_more'),
        ('quizzes', '0005_answer_answer_question_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['user'], name='quizresult_user_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user'], name='useranswer_user_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['quiz_result'], name='useranswer_quizresult_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['user'], name='usercourse_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user'], name='userprogress_user_idx'),
        ),
    ]
